// <auto-generated />
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EdTechAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251109183526_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Domains.Course", b =>
                {
                    b.Property<string>("CourseID")
                        .HasColumnType("TEXT")
                        .HasColumnName("course_id")
                        .HasAnnotation("Relational:JsonPropertyName", "courseid");

                    b.Property<string>("CourseContentURL")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("course_content_url")
                        .HasAnnotation("Relational:JsonPropertyName", "coursecontenturl");

                    b.Property<string>("CourseDescription")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("course_description")
                        .HasAnnotation("Relational:JsonPropertyName", "coursedescription");

                    b.Property<string>("CourseImageURL")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("course_image_url")
                        .HasAnnotation("Relational:JsonPropertyName", "courseimageurl");

                    b.Property<int>("CourseSizeBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("course_size_bytes")
                        .HasAnnotation("Relational:JsonPropertyName", "coursesizebytes");

                    b.Property<string>("CourseTitle")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("course_title")
                        .HasAnnotation("Relational:JsonPropertyName", "coursetitle");

                    b.Property<string>("CourseType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("course_type")
                        .HasAnnotation("Relational:JsonPropertyName", "coursetype");

                    b.Property<string>("CreatorID")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("creator_id")
                        .HasAnnotation("Relational:JsonPropertyName", "creatorid");

                    b.Property<int>("IsPublished")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_published")
                        .HasAnnotation("Relational:JsonPropertyName", "ispublished");

                    b.HasKey("CourseID");

                    b.ToTable("course_list");
                });
#pragma warning restore 612, 618
        }
    }
}
